actions test7

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,10 +1,10 @@
 name: Continuous Integration and Deployment
 
 on:
-    push:
-      branches: ["*"]  
-    pull_request:
-      branches: ["*"]
+  push:
+    branches: ["*"]  
+  pull_request:
+    branches: ["*"]
 
 env:
   REGISTRY: ghcr.io
@@ -17,19 +17,27 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
+      - name: Set up Python
+        uses: actions/setup-python@v4
         with:
-          node-version: '18'
+          python-version: '3.13-alpine'  # Укажите нужную версию Python
           
-      - name: Install dependencies
-        run: npm install
-        
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest
+          pip install -r requirements.txt  # Если есть файл с зависимостями
+          
       - name: Run tests
-        run: python -m pytest TestClient.py  
+        run: |
+          python -m pytest TestClient.py -v
+          if [ $? -ne 0 ]; then
+            echo "Tests failed"
+            exit 1
+          fi
 
   build-and-push-image:
-    needs: test  # Зависит от успешного выполнения job 'test'
+    needs: test
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -47,23 +55,16 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Extract metadata (tags, labels) for Docker
+      - name: Extract metadata
         id: meta
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-          tags: |
-            type=ref,event=branch
-            type=ref,event=pr
-            type=semver,pattern={{version}}
-            type=semver,pattern={{major}}.{{minor}}
-            type=semver,pattern={{major}}
 
       - name: Build and push Docker image
-        id: push
         uses: docker/build-push-action@v5
         with:
           context: .
-          push: ${{ github.event_name != 'pull_request' }}  
+          push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
